name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    # Set up Java JDK 17
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    
    # Build the project with Maven
    - name: Build with Maven
      run: mvn clean install -DskipTests --file pom.xml

    # Run tests with Maven (assuming tests are already part of the Maven build lifecycle)
    - name: Run tests
      run: mvn -Dtest=HerokuAppTestRunner test

    # Optional: Generate and upload Cucumber report (assuming Cucumber is configured to generate a report)
    - name: Upload Cucumber Report
      if: success()  # Only run if the tests pass
      uses: actions/upload-artifact@v3
      with:
        name: cucumber-report
        path: target/cucumber-reports/*  # Adjust path to where Cucumber stores its reports
